### ISSUE TITLE
OperatorSDK generated files with [.osdk.yaml] file type

### ISSUE THREAD

**Issue by jefflill** [nforgeio/operator-sdk#28]
What would you think of having the OperatorSDK generated file have a unique file type like **.osdk.yaml**, **ogen.yaml**, or something?

The idea here is to make it easy to **.gitignore** all of these files.  Right now, we're explicitly ignoring these by path, but that's fragile because it's very possible to to add a new RBAC conditions that will generate new files that will probably get tracked by Git until we figure that out and have to manually ignore them,

**Comment by marcusbooyah** [comment]
I changed the default extension to `.g.yaml` for now.
