### ISSUE TITLE
Generated rolebinding YAML is malformed

### ISSUE THREAD

**Issue by jefflill** [nforgeio/operator-sdk#30]
I've pulled **master** for all NEONFORGE repos and am seeing malformed rolebinding files being generated for **neon-cluster-operator** and **neon-cluster-agent**.  Here's an example:

![image](https://github.com/nforgeio/operator-sdk/assets/4908431/fd3af0bf-2935-4486-b46f-6bd0cceba216)

**Comment by marcusbooyah** [comment]
I'm not at my computer but it's [this](https://github.com/nforgeio/operator-sdk/blob/3c02ab9b6ce2302ae0010f9684d5e101e6ad855c/src/Neon.Operator.Analyzers/Generators/RbacRuleGenerator.cs#L572). I would also check for other instances of serializing twice.

**Comment by jefflill** [comment]
**FIXED:** This was the only place I found duplicate serialization.
